name: R-CMD-check-BiocCheck

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  BiocCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libfreetype6-dev libpng-dev libharfbuzz-dev libfribidi-dev pandoc

      - name: Install BiocManager
        run: |
          R -e "install.packages('BiocManager')"

      - name: Install all package dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'devtools'), repos = 'https://cran.rstudio.com/')"
          Rscript -e "BiocManager::install(c('BiocCheck', 'BiocStyle', 'testthat', 'knitr', 'rmarkdown', 'covr', 'rcmdcheck', 'lintr', 'styler'), update = FALSE, ask = FALSE)"
          Rscript -e "BiocManager::install(c('Seurat', 'dplyr', 'ggplot2', 'reshape2', 'e1071', 'caret', 'doParallel'), update = FALSE, ask = FALSE)"
          Rscript -e "BiocManager::install(c('PRROC', 'R.utils', 'pROC', 'randomForest', 'xgboost'), update = FALSE, ask = FALSE)"
          Rscript -e "remotes::install_deps(dependencies = TRUE, upgrade = 'never')"

      - name: Check package installation
        run: |
          R -e "if (!requireNamespace('scCulturePredict', quietly = TRUE)) { install.packages('.', repos = NULL, type = 'source') }"
          R -e "library(scCulturePredict)"

      - name: Check package
        run: |
          R -e "BiocCheck::BiocCheck('.')"

      - name: R CMD check
        run: |
          R -e "if (requireNamespace('devtools', quietly = TRUE)) { devtools::check() } else { message('devtools not available, skipping R CMD check'); rcmdcheck::rcmdcheck() }"

      - name: Run tests
        run: |
          R -e "devtools::test()"

      - name: Build vignettes
        run: |
          R -e "devtools::build_vignettes()"

      - name: Run code coverage
        run: |
          R -e "covr::package_coverage()"
          R -e "covr_report <- covr::report(covr::package_coverage()); dir.create('coverage_report', showWarnings = FALSE); saveRDS(covr_report, 'coverage_report/coverage.rds')"

      - name: Run linting checks
        run: |
          R -e "lintr::lint_package()"

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-results
          path: .

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report/

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
