# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check-BiocCheck

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3"
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libpng-dev \
            libharfbuzz-dev \
            libfribidi-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::BiocManager
            bioc::BiocCheck
            any::devtools
            any::covr
            any::testthat
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          error-on: '"never"'

      - name: Run BiocCheck
        if: always()
        run: |
          BiocCheck::BiocCheck(
            package = ".",
            `quit-with-status` = FALSE,
            `no-check-R-ver` = TRUE,
            `no-check-bioc-help` = TRUE
          )
        shell: Rscript {0}

      - name: Run tests
        if: always()
        run: |
          if (requireNamespace("testthat", quietly = TRUE)) {
            testthat::test_local()
          } else {
            message("testthat not available, skipping tests")
          }
        shell: Rscript {0}

      - name: Calculate coverage
        if: always()
        run: |
          if (requireNamespace("covr", quietly = TRUE)) {
            cov <- covr::package_coverage(
              type = "tests",
              quiet = FALSE
            )
            print(cov)
            covr::to_cobertura(cov, filename = "coverage.xml")
            message("Coverage report saved to coverage.xml")
          } else {
            message("covr not available, skipping coverage")
          }
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-results
          path: check

      - name: Test coverage
        if: always()
        run: |
          if (requireNamespace("covr", quietly = TRUE)) {
            cov <- covr::package_coverage(
              type = "tests",
              quiet = FALSE,
              clean = FALSE,
              install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
            )
            print(cov)
            covr::to_cobertura(cov, filename = "coverage.xml")
            message("Coverage XML report generated")
          } else {
            message("covr package not available, skipping coverage")
          }
        shell: Rscript {0}

      - name: Upload coverage reports
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
