# Minimal workflow for R CMD check and BiocCheck
name: check-bioc-minimal

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3"
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libpng-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libglpk-dev

      - name: Install BiocManager and set repositories
        run: |
          install.packages('BiocManager')
          BiocManager::install(version = '3.19', ask = FALSE)
        shell: Rscript {0}

      - name: Install package dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install('BiocCheck', ask = FALSE)
        shell: Rscript {0}

      - name: Check package
        run: |
          install.packages('rcmdcheck')
          rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning')
        shell: Rscript {0}

      - name: Run BiocCheck
        run: |
          BiocCheck::BiocCheck(
            package = '.',
            `quit-with-status` = FALSE,
            `no-check-R-ver` = TRUE,
            `no-check-bioc-help` = TRUE
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-results
          path: |
            *.out
            *.Rout
            *.Rcheck
